name: yaml_to_dart
description: Builder that transform yaml files into dart constants;

version: 1.0.1

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  build: ^1.1.6
  dart_style: ^1.3.3
  yaml: ^2.2.0

dev_dependencies:
  build_config: ^0.4.1+1
  test: ^1.9.4
  path: "^1.6.4"
