library yaml_to_dart;

import 'package:build/build.dart';
import 'package:dart_style/dart_style.dart';
import 'package:yaml/yaml.dart';
import 'package:yaml_to_dart/generator.dart';

class YAMLDartBuilder implements Builder {
  final BuilderOptions options;

  YAMLDartBuilder(this.options) : super();

  @override
  Map<String, List<String>> get buildExtensions => {
        '.yaml': ['.dart']
      };

  @override
  Future<void> build(BuildStep buildStep) async {
    final inputId = buildStep.inputId;
    final yamlContent = await buildStep.readAsString(inputId);
    AssetId dartFile = inputId.changeExtension('.dart');
    final dartCode = StringBuffer();
    final yamlMap = loadYaml(yamlContent);
    dartCode.write('// autogenerated, do not edit\n');
    generateClass(dartCode, '', 'messages', yamlMap, first: true);
    final formatter = new DartFormatter();
    await buildStep.writeAsString(
        dartFile, formatter.format(dartCode.toString()));
  }
}

Builder yamlToDart(BuilderOptions options) => YAMLDartBuilder(options);
